UI inputbox
DhairyaBahl/React-Messenger-App pull request #128
Opened 2021-03-31 10:35 UTC by akshay1027

UI of the input box is improved. Fixes #124.

2021-04-02 08:20 UTC, akshay1027 commented
necessary changes have been made!
![2021-04-02 (4)](https://user-images.githubusercontent.com/65683151/113397227-55589180-93ba-11eb-94a0-12a1ac9df767.png)

2021-04-02 10:15 UTC, dilemmawalker commented
Hey @DhairyaBahl , please have a look to verify final changes.

2021-04-05 18:37 UTC, DhairyaBahl commented
@akshay1027 Kindly squash all the commits ! Rest seems alright to me !

2021-04-05 18:40 UTC, DhairyaBahl requested changes

2021-04-05 18:40 UTC, DhairyaBahl commented on src/App.js
> -
You deleted this ! Is the app still working ?? Do send the gif or video for the same.

2021-04-05 18:40 UTC, DhairyaBahl commented on src/App.js
> -              </form>
Same goes with this one ! Kindly confirm it once with gif and screenshots !!

2021-04-05 18:42 UTC, akshay1027 commented
yep it is working! It is the second input box which i deleted before..!

2021-04-06 23:19 UTC, akshay1027 commented
https://drive.google.com/file/d/1QuNNAtDxow1hVa04lT_-YtfFIIgmqrka/view?usp=sharing , @DhairyaBahl  please check out this video! Website is working well! please check your mail as well!

2021-04-09 17:34 UTC, merged

2021-04-09 19:07 UTC, akshay1027 commented
can you please add labels to this PR, Thank you! @DhairyaBahl @dilemmawalker

2021-04-10 08:07 UTC, dilemmawalker commented
@akshay1027 please squash all the commits & then we can merge your pull request again.