Clean the codebase
DhairyaBahl/React-Messenger-App pull request #224
Opened 2021-05-13 10:57 UTC by garvitgupta13

Fix issue #217

Removed extra and unnecessary code and added useful comments to make it easy for developers to understand the codebase

2021-05-13 10:58 UTC, garvitgupta13 commented
YES

2021-05-14 13:05 UTC, abhijeet007rocks8 requested changes
Please resolve the merge conflicts

2021-05-14 13:22 UTC, garvitgupta13 commented
> Please resolve the merge conflicts

Please review my PR
I have solved the merge conflict

2021-05-14 13:27 UTC, abhijeet007rocks8 approved these changes

2021-05-14 13:27 UTC, merged