Made Scroll to Bottom Button Visible and Usable on Narrow Screens
DhairyaBahl/React-Messenger-App pull request #304
Opened 2021-05-20 14:27 UTC by N-Shar-ma

## Fixes #281

(Screenshots attached with the linked issue)

2021-05-20 14:27 UTC, N-Shar-ma commented
YES

2021-05-21 11:40 UTC, abhijeet007rocks8 requested changes
Resolve Merge Conflicts Please

2021-05-21 14:22 UTC, N-Shar-ma commented
> Resolve Merge Conflicts Please

Done!

2021-05-22 02:22 UTC, abhijeet007rocks8 approved these changes

2021-05-22 02:22 UTC, merged